// File generated by FlutterFire CLI. DO NOT EDIT.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'FirebaseOptions have not been configured for linux. '
          'Reconfigure with FlutterFire CLI if needed.',
        );
      default:
        throw UnsupportedError(
          'FirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJL6XdwpmdO-fAqmjix8CjLoAc5rFECiY',
    appId: '1:902531271733:web:a10aebfc345ede8ae7f57c',
    messagingSenderId: '902531271733',
    projectId: 'projecthandycraft-916a7',
    authDomain: 'projecthandycraft-916a7.firebaseapp.com',
    storageBucket: 'projecthandycraft-916a7.appspot.com',
    measurementId: 'G-0677HDFVY2',
    databaseURL: 'https://projecthandycraft-916a7-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVvRS6QdkImVHvJPDiB0DBi4tcYUj1KHk',
    appId: '1:902531271733:android:daf153ae720436e7e7f57c',
    messagingSenderId: '902531271733',
    projectId: 'projecthandycraft-916a7',
    storageBucket: 'projecthandycraft-916a7.appspot.com',
    databaseURL: 'https://projecthandycraft-916a7-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZcRPQSsqB2w2n_B4JUpMiyQcgj9Im8i8',
    appId: '1:902531271733:ios:e96855fcb4d5358ee7f57c',
    messagingSenderId: '902531271733',
    projectId: 'projecthandycraft-916a7',
    storageBucket: 'projecthandycraft-916a7.appspot.com',
    iosBundleId: 'com.example.handycraftApp',
    databaseURL: 'https://projecthandycraft-916a7-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZcRPQSsqB2w2n_B4JUpMiyQcgj9Im8i8',
    appId: '1:902531271733:ios:e96855fcb4d5358ee7f57c',
    messagingSenderId: '902531271733',
    projectId: 'projecthandycraft-916a7',
    storageBucket: 'projecthandycraft-916a7.appspot.com',
    iosBundleId: 'com.example.handycraftApp',
    databaseURL: 'https://projecthandycraft-916a7-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJL6XdwpmdO-fAqmjix8CjLoAc5rFECiY',
    appId: '1:902531271733:web:4f4c31e3230f7abbe7f57c',
    messagingSenderId: '902531271733',
    projectId: 'projecthandycraft-916a7',
    authDomain: 'projecthandycraft-916a7.firebaseapp.com',
    storageBucket: 'projecthandycraft-916a7.appspot.com',
    measurementId: 'G-87ZHZW5KDT',
    databaseURL: 'https://projecthandycraft-916a7-default-rtdb.firebaseio.com',
  );
}
